name: Bun
on: [pull_request, push]

jobs:
  bun:
    name: Bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install
      - run: bun test --timeout 10000000
      
